import type { LotteryConfig, LotterySlug } from "@/types/lottery";

export const LOTTERIES: Record<LotterySlug, LotteryConfig> = {
  megasena: {
    name: "Mega-Sena",
    slug: "megasena",
    numbers: { min: 1, max: 60, pick: 6, pickMax: 20 },
    color: "#209869",
    gradient: "from-emerald-500 to-green-700",
    description: "Escolha 6 números de 1 a 60",
    prizeDescription: "Acerte 6 números e ganhe milhões",
    drawDays: ["terça", "quinta", "sábado"],
    price: 5.0,
  },
  lotofacil: {
    name: "Lotofácil",
    slug: "lotofacil",
    numbers: { min: 1, max: 25, pick: 15, pickMax: 20 },
    color: "#930089",
    gradient: "from-purple-600 to-fuchsia-800",
    description: "Escolha 15 números de 1 a 25",
    prizeDescription: "A loteria mais fácil de ganhar",
    drawDays: ["segunda", "terça", "quarta", "quinta", "sexta", "sábado"],
    price: 3.0,
  },
  quina: {
    name: "Quina",
    slug: "quina",
    numbers: { min: 1, max: 80, pick: 5, pickMax: 15 },
    color: "#260085",
    gradient: "from-indigo-600 to-violet-900",
    description: "Escolha 5 números de 1 a 80",
    prizeDescription: "Sorteios de segunda a sábado",
    drawDays: ["segunda", "terça", "quarta", "quinta", "sexta", "sábado"],
    price: 2.5,
  },
  lotomania: {
    name: "Lotomania",
    slug: "lotomania",
    numbers: { min: 0, max: 99, pick: 50 },
    color: "#F78100",
    gradient: "from-orange-500 to-amber-700",
    description: "Escolha 50 números de 0 a 99",
    prizeDescription: "Acerte 20, 19, 18... ou nenhum!",
    drawDays: ["segunda", "quarta", "sexta"],
    price: 3.0,
  },
  timemania: {
    name: "Timemania",
    slug: "timemania",
    numbers: { min: 1, max: 80, pick: 10 },
    extraNumbers: { min: 1, max: 80, pick: 1 },
    color: "#00FF48",
    gradient: "from-lime-400 to-green-600",
    description: "Escolha 10 números de 1 a 80 + Time do Coração",
    prizeDescription: "Torça pelo seu time e ganhe",
    drawDays: ["terça", "quinta", "sábado"],
    price: 3.5,
  },
  duplasena: {
    name: "Dupla Sena",
    slug: "duplasena",
    numbers: { min: 1, max: 50, pick: 6, pickMax: 15 },
    color: "#A61324",
    gradient: "from-red-600 to-rose-800",
    description: "Escolha 6 números de 1 a 50 (2 sorteios)",
    prizeDescription: "Duas chances de ganhar por concurso",
    drawDays: ["terça", "quinta", "sábado"],
    price: 2.5,
  },
  federal: {
    name: "Federal",
    slug: "federal",
    numbers: { min: 0, max: 99999, pick: 1 },
    color: "#104A8E",
    gradient: "from-blue-600 to-sky-900",
    description: "Bilhetes com 5 algarismos",
    prizeDescription: "A loteria mais tradicional do Brasil",
    drawDays: ["quarta", "sábado"],
    price: 5.0,
  },
  diadesorte: {
    name: "Dia de Sorte",
    slug: "diadesorte",
    numbers: { min: 1, max: 31, pick: 7 },
    extraNumbers: { min: 1, max: 12, pick: 1 },
    color: "#CB852B",
    gradient: "from-yellow-500 to-orange-700",
    description: "Escolha 7 números de 1 a 31 + Mês da Sorte",
    prizeDescription: "Escolha seu mês da sorte",
    drawDays: ["terça", "quinta", "sábado"],
    price: 2.5,
  },
  supersete: {
    name: "Super Sete",
    slug: "supersete",
    numbers: { min: 0, max: 9, pick: 7 },
    color: "#A8CF45",
    gradient: "from-lime-500 to-emerald-600",
    description: "Escolha 1 número por coluna (7 colunas, 0 a 9)",
    prizeDescription: "O jogo dos 7 acertos",
    drawDays: ["segunda", "quarta", "sexta"],
    price: 2.5,
  },
  maismilionaria: {
    name: "+Milionária",
    slug: "maismilionaria",
    numbers: { min: 1, max: 50, pick: 6, pickMax: 12 },
    extraNumbers: { min: 1, max: 6, pick: 2, pickMax: 6 },
    color: "#2E3192",
    gradient: "from-indigo-700 to-blue-900",
    description: "Escolha 6 de 50 + 2 trevos de 1 a 6",
    prizeDescription: "A loteria dos grandes prêmios",
    drawDays: ["quarta", "sábado"],
    price: 6.0,
  },
};

export const LOTTERY_SLUGS = Object.keys(LOTTERIES) as LotterySlug[];

export const GENERATION_METHODS = [
  {
    id: "random" as const,
    name: "Aleatório",
    description: "Geração totalmente randômica",
    icon: "Shuffle",
  },
  {
    id: "frequency" as const,
    name: "Frequência",
    description: "Baseado nos números mais sorteados",
    icon: "BarChart3",
  },
  {
    id: "hot-cold" as const,
    name: "Quentes/Frios",
    description: "Análise dos últimos concursos",
    icon: "Flame",
  },
  {
    id: "statistical" as const,
    name: "Estatístico",
    description: "Análise de probabilidade avançada",
    icon: "TrendingUp",
  },
  {
    id: "smart-filter" as const,
    name: "Filtro Inteligente",
    description: "Defina seus próprios critérios",
    icon: "SlidersHorizontal",
  },
  {
    id: "ai" as const,
    name: "Inteligência Artificial",
    description: "Sugestões baseadas em IA",
    icon: "Brain",
  },
] as const;
